language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t libsmbios-debian-unstable -f pkg/dockerfiles/Dockerfile-debian-unstable .

script:
  - docker run -t -v `pwd`:/build libsmbios-debian-unstable ./pkg/build_and_test.sh
