FROM debian:unstable

RUN echo "deb-src http://deb.debian.org/debian/ unstable main" >> /etc/apt/sources.list
RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends \
	build-essential \
	autotools-dev \
	doxygen \
	graphviz \
	python \
	chrpath \
	libxml2-dev \
	pkg-config \
	autoconf \
	automake \
	libtool \
	libcppunit-dev \
	gettext \
	autopoint
RUN mkdir /build
WORKDIR /build
