'\" te
.\"  Copyright 2010 Dell
.\"|[amp   ]
.\"|T  Copyright (c) 1983 Regents of the University of California\&.  All rights reserved\&.  The Berkeley software License Agreement  specifies the terms and conditions for redistribution\&.  Copyright (c) 2003, Sun Microsystems, Inc\&.  All Rights Reserved  Portions Copyright (c) 1992, X/Open Company Limited  All Rights Reserved
.TH dellBiosUpdate 4 "01 Aug 2010" "SunOS 5.10" "User Commands"
.SH "NAME"
dellBiosUpdate \- Update Dell BIOS
.SH "SYNOPSIS"
.PP
\fBdellBiosUpdate\fR [--\fBhdr\fR | -\fBf\fR] <file> [--\fBupdate\fR | -\fBu\fR]\fI
.PP
\fBdellBiosUpdate\fR [--\fBhdr\fR | -\fBf\fR] <file> [--\fBtest\fR | -\fBt\fR]\fI
.PP
\fBdellBiosUpdate\fR [--\fBhdr\fR | -\fBf\fR] <file> [--\fBinfo\fR | -\fBi\fR]\fI
.PP
\fBdellBiosUpdate\fR [--\fBcancel\fR | -\fBc\fR]\fI
.SH "DESCRIPTION"
.PP
The \fBdellBiosUpdate\fR utility will update the BIOS on a Dell system.  The utility does not update the BIOS directly, but causes a BIOS update to occur on the next reboot\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBf\fR \fR
.in +9n
.rt
Specifies the .HDR file to use for the BIOS Update\&. See below for how to obtain the .HDR file for the system\&.
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB-\fBu\fR \fR
.in +9n
.rt
Update the BIOS.  Requires the -f <file> header file to be specified\&.
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB-\fBi\fR \fR
.in +9n
.rt
Display information about the BIOS hdr file.  Requires the -f <file> header file to be specified\&.
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB-\fBc\fR \fR
.in +9n
.rt
Cancel pending BIOS update\&.
.sp
.sp 1
.in -9n
.SH "SECURITY"
.PP
The dellBiosUpdate utility must be run as the superuser\&.
.SH "SEE MORE"
.PP
\fBObtaining BIOS .hdr files\fR
.sp
.in +9n
The BIOS update utility does not come with the required BIOS .hdr files for the system.  These .hdr files must be obtained from the support.dell.com website.
.in -9n
