'\" te
.\"  Copyright 2010 Dell
.\"|[amp   ]
.\"|T  Copyright (c) 1983 Regents of the University of California\&.  All rights reserved\&.  The Berkeley software License Agreement  specifies the terms and conditions for redistribution\&.  Copyright (c) 2003, Sun Microsystems, Inc\&.  All Rights Reserved  Portions Copyright (c) 1992, X/Open Company Limited  All Rights Reserved
.TH smbios-sys-info 4 "01 Aug 2010" "SunOS 5.10" "User Commands"
.SH "NAME"
smbios-sys-info \- Display System Info
.SH "SYNOPSIS"
.PP
\fBsmbios-sys-info\fR
.SH "DESCRIPTION"
.PP
The \fBsmbios-sys-info\fR utility will display the System Hardware ID, Service Tag, Asset Tag, Product Name and BIOS Version
